# ------------------------------
# OpenAI
# ------------------------------
# GPT-3.5 models
gpt-3.5-turbo-0125:
  model_name: GPT-3.5 Turbo
  provider: openai
  release_date: 2024-01-25

# GPT-4o models
gpt-4o-mini-2024-07-18:
  model_name: GPT-4o mini
  provider: openai
  release_date: 2024-07-18

gpt-4o-2024-08-06:
  model_name: GPT-4o
  provider: openai
  release_date: 2024-08-06

# oX models
o1-mini-2024-09-12:
  model_name: o1-mini
  provider: openai
  release_date: 2024-09-12
  reasoning_model: true
  accepts_system_message: false
  temperature: 1.0
  max_completion_tokens: 16000

o3-mini-2025-01-31:low:
  model_name: o3-mini (low)
  provider: openai
  release_date: 2025-01-31
  reasoning_model: true
  reasoning_effort: low
  temperature: 1.0
  max_completion_tokens: 16000

o3-mini-2025-01-31:medium:
  model_name: o3-mini (medium)
  provider: openai
  release_date: 2025-01-31
  reasoning_model: true
  reasoning_effort: medium
  temperature: 1.0
  max_completion_tokens: 16000

o3-mini-2025-01-31:high:
  model_name: o3-mini (high)
  provider: openai
  release_date: 2025-01-31
  reasoning_model: true
  reasoning_effort: high
  temperature: 1.0
  max_completion_tokens: 16000


# ------------------------------
# Anthropic
# ------------------------------
# Claude 3.5 models
claude-3-5-haiku-20241022:
  model_name: Claude 3.5 Haiku
  provider: anthropic
  release_date: 2024-10-22

claude-3-5-sonnet-20240620:
  model_name: Claude 3.5 Sonnet
  provider: anthropic
  release_date: 2024-06-20

claude-3-5-sonnet-20241022:
  model_name: Claude 3.5 Sonnet v2
  provider: anthropic
  release_date: 2024-10-22

# Claude 3.7 models
claude-3-7-sonnet-20250219:
  model_name: Claude 3.7 Sonnet
  provider: anthropic
  release_date: 2025-02-19

claude-3-7-sonnet-20250219:thinking:
  model_name: Claude 3.7 Sonnet (thinking)
  provider: anthropic
  release_date: 2025-02-19
  reasoning_model: true
  temperature: 1.0
  max_completion_tokens: 16000


# ------------------------------
# Gemini
# ------------------------------
# Gemini 1.5 models
gemini-1.5-flash-8b-001:
  model_name: Gemini 1.5 Flash 8B
  provider: gemini
  release_date: 2024-09-23

gemini-1.5-flash-002:
  model_name: Gemini 1.5 Flash
  provider: gemini
  release_date: 2024-09-23

gemini-1.5-pro-002:
  model_name: Gemini 1.5 Pro
  provider: gemini
  release_date: 2024-09-23

# Gemini 2.0 models
gemini-2.0-flash-lite-001:
  model_name: Gemini 2 Flash Lite
  provider: gemini
  release_date: 2025-02-25

gemini-2.0-flash-001:
  model_name: Gemini 2 Flash
  provider: gemini
  release_date: 2025-01-30

gemini-2.0-flash-thinking-exp:
  model_name: Gemini 2 Flash Thinking
  provider: gemini
  reasoning_model: true
  temperature: 1.0
  max_completion_tokens: 16000

# Gemini 2.5 models
gemini-2.5-pro-preview-03-25:
  model_name: Gemini 2.5 Pro Preview
  provider: gemini
  release_date: 2025-03-25


# ------------------------------
# OpenRouter
# ------------------------------
# Llama 4 models
meta-llama/llama-4-scout:
  model_name: Llama 4 Scout
  provider: openrouter
  release_date: 2025-04-05
  provider_routing: [Groq] # https://openrouter.ai/meta-llama/llama-4-scout

meta-llama/llama-4-maverick:
  model_name: Llama 4 Maverick
  provider: openrouter
  release_date: 2025-04-05
  provider_routing: [Groq] # https://openrouter.ai/meta-llama/llama-4-maverick

# Llama 3.X models
meta-llama/llama-3.1-8b-instruct:
  model_name: Llama 3.1 8B
  provider: openrouter
  release_date: 2024-07-23
  provider_routing: [Lambda, InferenceNet] # https://openrouter.ai/meta-llama/llama-3-8b-instruct

meta-llama/llama-3.1-70b-instruct:
  model_name: Llama 3.1 70B
  provider: openrouter
  release_date: 2024-07-23
  provider_routing: [SambaNova, Friendli]

meta-llama/llama-3.1-405b-instruct:
  model_name: Llama 3.1 405B
  provider: openrouter
  release_date: 2024-07-23
  provider_routing: [Lambda, DeepInfra] # https://openrouter.ai/meta-llama/llama-3.1-405b-instruct

meta-llama/llama-3.3-70b-instruct:
  model_name: Llama 3.3 70B
  provider: openrouter
  release_date: 2024-12-06
  provider_routing: [Groq, SambaNova] # https://openrouter.ai/meta-llama/llama-3.3-70b-instruct

# Qwen models
qwen/qwen-2.5-7b-instruct:
  model_name: Qwen 2.5 7B
  provider: openrouter
  release_date: 2024-09-19
  provider_routing: [DeepInfra]

qwen/qwen2.5-32b-instruct:
  model_name: Qwen 2.5 32B
  provider: openrouter
  release_date: 2024-09-19
  provider_routing: [Groq]

qwen/qwen-2.5-72b-instruct:
  model_name: Qwen 2.5 72B
  provider: openrouter
  release_date: 2024-09-19
  provider_routing: [Fireworks] #, SambaNova, Nebius AI Studio]

qwen/qwen-turbo:
  model_name: Qwen Turbo
  provider: openrouter
  release_date: 2025-01-25
  provider_routing: [Alibaba]

qwen/qwen-plus:
  model_name: Qwen Plus
  provider: openrouter
  release_date: 2025-01-25
  provider_routing: [Alibaba]

qwen/qwen-max:
  model_name: Qwen Max
  provider: openrouter
  release_date: 2025-01-25
  provider_routing: [Alibaba]

qwen/qwq-32b:
  model_name: QwQ 32B
  provider: openrouter
  release_date: 2025-03-06
  reasoning_model: true
  provider_routing: [Groq, DeepInfra]
  temperature: 0.6
  max_completion_tokens: 16000

# Microsoft models
microsoft/phi-4:
  model_name: Phi-4
  provider: openrouter
  release_date: 2024-12-12
  provider_routing: [Nebius, DeepInfra]

# DeepSeek models
deepseek/deepseek-chat:
  model_name: DeepSeek V3
  provider: openrouter
  release_date: 2024-12-26
  provider_routing: [Fireworks, Novita] # https://openrouter.ai/deepseek/deepseek-chat

deepseek/deepseek-chat-v3-0324:
  model_name: DeepSeek V3 0324
  provider: openrouter
  release_date: 2025-03-24
  provider_routing: [Novita] # [SambaNova] # https://openrouter.ai/deepseek/deepseek-chat-v3-0324

deepseek/deepseek-r1:
  model_name: DeepSeek R1
  provider: openrouter
  release_date: 2025-01-20
  reasoning_model: true
  provider_routing: [Parasail, InferenceNet] # https://openrouter.ai/deepseek/deepseek-r1
  temperature: 0.6
  max_completion_tokens: 16000

deepseek/deepseek-r1-zero:free: # rate limit of 20 req/min and 200 req/day
  model_name: DeepSeek R1 Zero
  provider: openrouter
  release_date: 2025-01-20
  reasoning_model: true
  provider_routing: [Chutes] # https://openrouter.ai/deepseek/deepseek-r1-zero:free
  temperature: 0.6
  max_completion_tokens: 16000

deepseek/deepseek-r1-distill-qwen-32b:
  model_name: DeepSeek R1 Distill Qwen 32B
  provider: openrouter
  release_date: 2025-01-20
  reasoning_model: true
  provider_routing: [Groq]
  temperature: 0.6
  max_completion_tokens: 16000

deepseek/deepseek-r1-distill-llama-70b:
  model_name: DeepSeek R1 Distill Llama 70B
  provider: openrouter
  release_date: 2025-01-20
  reasoning_model: true
  provider_routing: [Groq, SambaNova]
  temperature: 0.6
  max_completion_tokens: 16000

# Other models
openrouter/quasar-alpha:
  model_name: Quasar Alpha
  provider: openrouter
  release_date: 2025-04-04
  # provider_routing: [Stealth]

openrouter/optimus-alpha:
  model_name: Optimus Alpha
  provider: openrouter
  release_date: 2025-04-10
  # provider_routing: [Stealth]


# ------------------------------
# Hugging Face
# ------------------------------
meta-llama/Llama-3.2-1B-Instruct:
  model_name: Llama 3.2 1B
  provider: huggingface
  release_date: 2024-09-25

# Gemma 3 models
google/gemma-3-1b-it:
  model_name: Gemma 3 1B
  provider: huggingface
  release_date: 2025-03-10

google/gemma-3-4b-it:
  model_name: Gemma 3 4B
  provider: huggingface
  release_date: 2025-03-10

google/gemma-3-12b-it:
  model_name: Gemma 3 12B
  provider: huggingface
  release_date: 2025-03-10

google/gemma-3-27b-it:
  model_name: Gemma 3 27B
  provider: huggingface
  release_date: 2025-03-10

# microsoft/Phi-4-mini-instruct:
#   model_name: Phi-4 Mini
#   provider: huggingface
# microsoft/phi-4:
#   model_name: Phi-4
#   provider: huggingface

# OLMo 2 7B models
allenai/OLMo-2-1124-7B-SFT:
  model_name: OLMo 2 7B SFT
  provider: huggingface
  release_date: 2024-11-24

allenai/OLMo-2-1124-7B-DPO:
  model_name: OLMo 2 7B DPO
  provider: huggingface
  release_date: 2024-11-24

allenai/OLMo-2-1124-7B:
  model_name: OLMo 2 7B RLVR
  provider: huggingface
  release_date: 2024-11-24

# OLMo 2 13B models
allenai/OLMo-2-1124-13B-SFT:
  model_name: OLMo 2 13B SFT
  provider: huggingface
  release_date: 2024-11-24

allenai/OLMo-2-1124-13B-DPO:
  model_name: OLMo 2 13B DPO
  provider: huggingface
  release_date: 2024-11-24

allenai/OLMo-2-1124-13B-Instruct:
  model_name: OLMo 2 13B RLVR
  provider: huggingface
  release_date: 2024-11-24

# OLMo 2 32B models
allenai/OLMo-2-0325-32B-SFT:
  model_name: OLMo 2 32B SFT
  provider: huggingface
  release_date: 2025-03-25

allenai/OLMo-2-0325-32B-DPO:
  model_name: OLMo 2 32B DPO
  provider: huggingface
  release_date: 2025-03-25

allenai/OLMo-2-0325-32B-Instruct:
  model_name: OLMo 2 32B RLVR
  provider: huggingface
  release_date: 2025-03-25

# Tülu 3 8B models
allenai/Llama-3.1-Tulu-3-8B-SFT:
  model_name: Tülu 3 8B SFT
  provider: huggingface
  release_date: 2024-11-21

allenai/Llama-3.1-Tulu-3-8B-DPO:
  model_name: Tülu 3 8B DPO
  provider: huggingface
  release_date: 2024-11-21

allenai/Llama-3.1-Tulu-3-8B:
  model_name: Tülu 3 8B RLVR
  provider: huggingface
  release_date: 2024-11-21

# Tülu 3 70B models
allenai/Llama-3.1-Tulu-3-70B-SFT:
  model_name: Tülu 3 70B SFT
  provider: huggingface
  release_date: 2024-11-21

allenai/Llama-3.1-Tulu-3-70B-DPO:
  model_name: Tülu 3 70B DPO
  provider: huggingface
  release_date: 2024-11-21

allenai/Llama-3.1-Tulu-3-70B:
  model_name: Tülu 3 70B RLVR
  provider: huggingface
  release_date: 2024-11-21

# Tülu V2.5 PPO models
allenai/tulu-v2.5-ppo-13b-hh-rlhf-60k:
  model_name: Tülu V2.5 13B PPO HH RLHF
  provider: huggingface
  release_date: 2024-06-11

allenai/tulu-v2.5-ppo-13b-chatbot-arena-2023:
  model_name: Tülu V2.5 13B PPO ChatbotArena
  provider: huggingface
  release_date: 2024-06-11

allenai/tulu-v2.5-ppo-13b-stackexchange-60k:
  model_name: Tülu V2.5 13B PPO StackExchange
  provider: huggingface
  release_date: 2024-06-11

allenai/tulu-v2.5-ppo-13b-nectar-60k:
  model_name: Tülu V2.5 13B PPO Nectar
  provider: huggingface
  release_date: 2024-06-11

# Tülu V2.5 DPO models
allenai/tulu-v2.5-dpo-13b-hh-rlhf-60k:
  model_name: Tülu V2.5 13B DPO HH RLHF
  provider: huggingface
  release_date: 2024-06-11

allenai/tulu-v2.5-dpo-13b-chatbot-arena-2023:
  model_name: Tülu V2.5 13B DPO ChatbotArena
  provider: huggingface
  release_date: 2024-06-11

allenai/tulu-v2.5-dpo-13b-stackexchange-60k:
  model_name: Tülu V2.5 13B DPO StackExchange
  provider: huggingface
  release_date: 2024-06-11

allenai/tulu-v2.5-dpo-13b-nectar-60k:
  model_name: Tülu V2.5 13B DPO Nectar
  provider: huggingface
  release_date: 2024-06-11

# Nous-Hermes models
NousResearch/Nous-Hermes-2-Mixtral-8x7B-SFT:
  model_name: Hermes 2 Mixtral 8x7B SFT
  provider: huggingface
  release_date: 2024-04-15

NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO:
  model_name: Hermes 2 Mixtral 8x7B DPO
  provider: huggingface
  release_date: 2024-04-15