# ------------------------------
# OpenAI
# ------------------------------
# GPT-3.5 models
gpt-3.5-turbo-1106:
  model_name: GPT-3.5 Turbo 1106
  provider: openai
  release_date: 2023-11-06
  developer: OpenAI

gpt-3.5-turbo-0125:
  model_name: GPT-3.5 Turbo 0125
  provider: openai
  release_date: 2024-01-25
  developer: OpenAI

# GPT-4o models
gpt-4o-mini-2024-07-18:
  model_name: GPT-4o mini
  provider: openai
  release_date: 2024-07-18
  developer: OpenAI

gpt-4o-2024-05-13:
  model_name: GPT-4o 0513
  provider: openai
  release_date: 2024-05-13
  developer: OpenAI

gpt-4o-2024-08-06:
  model_name: GPT-4o 0806
  provider: openai
  release_date: 2024-08-06
  developer: OpenAI

gpt-4o-2024-11-20:
  model_name: GPT-4o 1120
  provider: openai
  release_date: 2024-11-20
  developer: OpenAI

# GPT-4.1 models
gpt-4.1-2025-04-14:
  model_name: GPT-4.1
  provider: openai
  release_date: 2025-04-14
  developer: OpenAI

gpt-4.1-mini-2025-04-14:
  model_name: GPT-4.1 mini
  provider: openai
  release_date: 2025-04-14
  developer: OpenAI

gpt-4.1-nano-2025-04-14:
  model_name: GPT-4.1 nano
  provider: openai
  release_date: 2025-04-14
  developer: OpenAI

# oX models
o1-mini-2024-09-12:
  model_name: o1-mini
  provider: openai
  release_date: 2024-09-12
  reasoning_model: true
  accepts_system_message: false
  temperature: 1.0
  max_completion_tokens: 16000
  developer: OpenAI

o3-mini-2025-01-31:low:
  model_name: o3-mini (low)
  provider: openai
  release_date: 2025-01-31
  reasoning_model: true
  reasoning_effort: low
  temperature: 1.0
  max_completion_tokens: 16000
  developer: OpenAI

o3-mini-2025-01-31:medium:
  model_name: o3-mini (medium)
  provider: openai
  release_date: 2025-01-31
  reasoning_model: true
  reasoning_effort: medium
  temperature: 1.0
  max_completion_tokens: 16000
  developer: OpenAI

o3-mini-2025-01-31:high:
  model_name: o3-mini (high)
  provider: openai
  release_date: 2025-01-31
  reasoning_model: true
  reasoning_effort: high
  temperature: 1.0
  max_completion_tokens: 16000
  developer: OpenAI


# ------------------------------
# Anthropic
# ------------------------------
# Claude 3 models
claude-3-haiku-20240307:
  model_name: Claude 3 Haiku
  provider: anthropic
  release_date: 2024-03-07
  developer: Anthropic

claude-3-sonnet-20240229:
  model_name: Claude 3 Sonnet
  provider: anthropic
  release_date: 2024-02-29
  developer: Anthropic

# Claude 3.5 models
claude-3-5-haiku-20241022:
  model_name: Claude 3.5 Haiku
  provider: anthropic
  release_date: 2024-10-22
  developer: Anthropic

claude-3-5-sonnet-20240620:
  model_name: Claude 3.5 Sonnet
  provider: anthropic
  release_date: 2024-06-20
  developer: Anthropic

claude-3-5-sonnet-20241022:
  model_name: Claude 3.5 Sonnet v2
  provider: anthropic
  release_date: 2024-10-22
  developer: Anthropic

# Claude 3.7 models
claude-3-7-sonnet-20250219:
  model_name: Claude 3.7 Sonnet
  provider: anthropic
  release_date: 2025-02-19
  developer: Anthropic

claude-3-7-sonnet-20250219:thinking:
  model_name: Claude 3.7 Sonnet (thinking)
  provider: anthropic
  release_date: 2025-02-19
  reasoning_model: true
  temperature: 1.0
  max_completion_tokens: 16000
  developer: Anthropic


# ------------------------------
# Gemini
# ------------------------------
# Gemini 1.5 models
gemini-1.5-flash-8b-001:
  model_name: Gemini 1.5 Flash 8B
  provider: gemini
  release_date: 2024-09-24
  developer: Google

gemini-1.5-flash-002:
  model_name: Gemini 1.5 Flash
  provider: gemini
  release_date: 2024-09-24
  developer: Google

gemini-1.5-pro-002:
  model_name: Gemini 1.5 Pro
  provider: gemini
  release_date: 2024-09-24
  developer: Google

# Gemini 2.0 models
gemini-2.0-flash-lite-001:
  model_name: Gemini 2 Flash Lite
  provider: gemini
  release_date: 2025-02-25
  developer: Google

gemini-2.0-flash-001:
  model_name: Gemini 2 Flash
  provider: gemini
  release_date: 2025-02-05
  developer: Google

gemini-2.0-flash-thinking-exp:
  model_name: Gemini 2 Flash Thinking
  provider: gemini
  reasoning_model: true
  temperature: 1.0
  max_completion_tokens: 16000
  developer: Google

# Gemini 2.5 models
gemini-2.5-pro-preview-03-25:
  model_name: Gemini 2.5 Pro Preview
  provider: gemini
  release_date: 2025-03-25
  num_concurrent: 20
  max_rate: 150
  period: 60
  max_completion_tokens: 16000
  developer: Google

gemini-2.5-flash-preview-04-17:
  model_name: Gemini 2.5 Flash Preview
  provider: gemini
  release_date: 2025-04-17
  developer: Google


# ------------------------------
# OpenRouter
# ------------------------------
# Llama 4 models
meta-llama/llama-4-scout:
  model_name: Llama 4 Scout
  provider: openrouter
  release_date: 2025-04-05
  provider_routing: [Groq] # https://openrouter.ai/meta-llama/llama-4-scout
  developer: Meta

meta-llama/llama-4-maverick:
  model_name: Llama 4 Maverick
  provider: openrouter
  release_date: 2025-04-05
  provider_routing: [Fireworks] # https://openrouter.ai/meta-llama/llama-4-maverick
  developer: Meta

# Llama 3.X models
meta-llama/llama-3-8b-instruct:
  model_name: Llama 3 8B
  provider: openrouter
  release_date: 2024-04-18
  provider_routing: [DeepInfra, Groq] # https://openrouter.ai/meta-llama/llama-3-8b-instruct
  developer: Meta

meta-llama/llama-3-70b-instruct:
  model_name: Llama 3 70B
  provider: openrouter
  release_date: 2024-04-18
  provider_routing: [Groq] # https://openrouter.ai/meta-llama/llama-3-70b-instruct
  developer: Meta

meta-llama/llama-3.1-8b-instruct:
  model_name: Llama 3.1 8B
  provider: openrouter
  release_date: 2024-07-23
  provider_routing: [Groq, Lambda, InferenceNet] # https://openrouter.ai/meta-llama/llama-3-8b-instruct
  developer: Meta

meta-llama/llama-3.1-70b-instruct:
  model_name: Llama 3.1 70B
  provider: openrouter
  release_date: 2024-07-23
  provider_routing: [Nebius, Fireworks]
  developer: Meta

meta-llama/llama-3.1-405b-instruct:
  model_name: Llama 3.1 405B
  provider: openrouter
  release_date: 2024-07-23
  provider_routing: [Lambda, DeepInfra] # https://openrouter.ai/meta-llama/llama-3.1-405b-instruct
  developer: Meta

meta-llama/llama-3.3-70b-instruct:
  model_name: Llama 3.3 70B
  provider: openrouter
  release_date: 2024-12-06
  provider_routing: [Groq, SambaNova] # https://openrouter.ai/meta-llama/llama-3.3-70b-instruct
  developer: Meta

# Qwen models
qwen/qwen-2.5-7b-instruct:
  model_name: Qwen 2.5 7B
  provider: openrouter
  release_date: 2024-09-19
  provider_routing: [DeepInfra]
  developer: Alibaba

qwen/qwen2.5-32b-instruct:
  model_name: Qwen 2.5 32B
  provider: openrouter
  release_date: 2024-09-19
  provider_routing: [Groq]
  developer: Alibaba

qwen/qwen-2.5-72b-instruct:
  model_name: Qwen 2.5 72B
  provider: openrouter
  release_date: 2024-09-19
  provider_routing: [Fireworks] #, SambaNova, Nebius AI Studio]
  developer: Alibaba

qwen/qwen-turbo:
  model_name: Qwen Turbo
  provider: openrouter
  release_date: 2025-01-25
  provider_routing: [Alibaba]
  developer: Alibaba

qwen/qwen-plus:
  model_name: Qwen Plus
  provider: openrouter
  release_date: 2025-01-25
  provider_routing: [Alibaba]
  developer: Alibaba

qwen/qwen-max:
  model_name: Qwen Max
  provider: openrouter
  release_date: 2025-01-25
  provider_routing: [Alibaba]
  developer: Alibaba

qwen/qwq-32b:
  model_name: QwQ 32B
  provider: openrouter
  release_date: 2025-03-06
  reasoning_model: true
  provider_routing: [Groq] # [Novita, DeepInfra]
  temperature: 0.6
  max_completion_tokens: 16384
  developer: Alibaba

# THUDM models
thudm/glm-4-32b:
  model_name: GLM-4 32B
  provider: openrouter
  release_date: 2025-04-17
  provider_routing: [Novita]
  developer: THUDM

thudm/glm-z1-32b:
  model_name: GLM-4 32B
  provider: openrouter
  release_date: 2025-04-17
  reasoning_model: true
  provider_routing: [Novita]
  temperature: 0.6
  max_completion_tokens: 16384
  developer: THUDM

# Microsoft models
microsoft/phi-4:
  model_name: Phi-4
  provider: openrouter
  release_date: 2024-12-12
  provider_routing: [Nebius, DeepInfra]
  developer: Microsoft

microsoft/phi-3.5-mini-128k-instruct:
  model_name: Phi-3.5 Mini
  provider: openrouter
  release_date: 2024-08-16
  # provider_routing: [Azure]  # Very slow
  developer: Microsoft

microsoft/phi-3-medium-128k-instruct:
  model_name: Phi-3 Medium
  provider: openrouter
  release_date: 2024-05-02
  # provider_routing: [Azure]
  developer: Microsoft

microsoft/phi-3-mini-128k-instruct:
  model_name: Phi-3 Mini
  provider: openrouter
  release_date: 2024-05-02
  # provider_routing: [Azure]
  developer: Microsoft

# DeepSeek models
deepseek/deepseek-chat:
  model_name: DeepSeek V3
  provider: openrouter
  release_date: 2024-12-26
  provider_routing: [Fireworks] # https://openrouter.ai/deepseek/deepseek-chat
  developer: DeepSeek

deepseek/deepseek-chat-v3-0324:
  model_name: DeepSeek V3 0324
  provider: openrouter
  release_date: 2025-03-24
  provider_routing: [Lambda] # [SambaNova] # https://openrouter.ai/deepseek/deepseek-chat-v3-0324
  developer: DeepSeek

deepseek/deepseek-r1:
  model_name: DeepSeek R1
  provider: openrouter
  release_date: 2025-01-20
  reasoning_model: true
  provider_routing: [Lambda] # https://openrouter.ai/deepseek/deepseek-r1
  temperature: 0.6
  max_completion_tokens: 16384
  developer: DeepSeek

deepseek/deepseek-r1-distill-qwen-32b:
  model_name: DeepSeek R1 Distill Qwen 32B
  provider: openrouter
  release_date: 2025-01-20
  reasoning_model: true
  provider_routing: [Groq]
  temperature: 0.6
  max_completion_tokens: 16384
  developer: DeepSeek

deepseek/deepseek-r1-distill-llama-70b:
  model_name: DeepSeek R1 Distill Llama 70B
  provider: openrouter
  release_date: 2025-01-20
  reasoning_model: true
  provider_routing: [Groq]
  temperature: 0.6
  max_completion_tokens: 16384
  developer: DeepSeek


# Google models via OpenRouter
google/gemini-2.5-pro-preview-03-25:
  model_name: Gemini 2.5 Pro Preview
  provider: openrouter
  release_date: 2025-03-25
  num_concurrent: 20
  max_rate: 150
  period: 60
  developer: Google
  # provider_routing: [Google AI Studio]

google/gemini-2.5-flash-preview:
  model_name: Gemini 2.5 Flash Preview
  provider: openrouter
  release_date: 2025-04-17
  developer: Google

google/gemini-2.0-flash-001:
  model_name: Gemini 2 Flash
  provider: openrouter
  release_date: 2025-02-05
  developer: Google

google/gemini-2.0-flash-lite-001:
  model_name: Gemini 2 Flash Lite
  provider: openrouter
  release_date: 2025-02-25
  developer: Google

google/gemini-pro-1.5:
  model_name: Gemini Pro 1.5
  provider: openrouter
  release_date: 2024-09-24
  developer: Google

google/gemini-flash-1.5:
  model_name: Gemini 1.5 Flash
  provider: openrouter
  release_date: 2024-09-24
  developer: Google

google/gemini-flash-1.5-8b:
  model_name: Gemini 1.5 Flash 8B
  provider: openrouter
  release_date: 2024-09-24
  developer: Google

google/gemini-pro:
  model_name: Gemini Pro
  provider: openrouter
  release_date: 2024-04-09
  developer: Google

google/gemma-3-4b-it:
  model_name: Gemma 3 4B
  provider: openrouter
  release_date: 2025-03-10
  developer: Google

google/gemma-3-12b-it:
  model_name: Gemma 3 12B
  provider: openrouter
  release_date: 2025-03-10
  developer: Google

google/gemma-3-27b-it:
  model_name: Gemma 3 27B
  provider: openrouter
  release_date: 2025-03-10
  provider_routing: [DeepInfra, Parasail]
  developer: Google

# Anthropic model via OpenRouter
anthropic/claude-3-haiku:beta:
  model_name: Claude 3 Haiku
  provider: openrouter
  release_date: 2024-03-07
  developer: Anthropic

anthropic/claude-3-sonnet:beta:
  model_name: Claude 3 Sonnet
  provider: openrouter
  release_date: 2024-02-29
  developer: Anthropic

anthropic/claude-3.5-sonnet-20240620:beta:
  model_name: Claude 3.5 Sonnet
  provider: openrouter
  release_date: 2024-06-20
  developer: Anthropic

anthropic/claude-3.5-haiku:beta:
  model_name: Claude 3.5 Haiku
  provider: openrouter
  release_date: 2024-10-22
  developer: Anthropic

anthropic/claude-3.5-sonnet:beta:
  model_name: Claude 3.5 Sonnet v2
  provider: openrouter
  release_date: 2024-10-22
  developer: Anthropic

anthropic/claude-3.7-sonnet:beta:
  model_name: Claude 3.7 Sonnet
  provider: openrouter
  release_date: 2025-02-19
  developer: Anthropic


# ------------------------------
# Hugging Face
# ------------------------------
meta-llama/Llama-3.2-1B-Instruct:
  model_name: Llama 3.2 1B
  provider: huggingface
  release_date: 2024-09-25
  developer: Meta

# Gemma 3 models
# google/gemma-3-1b-it:
#   model_name: Gemma 3 1B
#   provider: huggingface
#   release_date: 2025-03-10
#   developer: Google

# google/gemma-3-4b-it:
#   model_name: Gemma 3 4B
#   provider: huggingface
#   release_date: 2025-03-10
#   developer: Google

# google/gemma-3-12b-it:
#   model_name: Gemma 3 12B
#   provider: huggingface
#   release_date: 2025-03-10
#   developer: Google

# google/gemma-3-27b-it:
#   model_name: Gemma 3 27B
#   provider: huggingface
#   release_date: 2025-03-10
#   developer: Google

# microsoft/Phi-4-mini-instruct:
#   model_name: Phi-4 Mini
#   provider: huggingface
#   developer: Microsoft

# microsoft/phi-4:
#   model_name: Phi-4
#   provider: huggingface
#   developer: Microsoft

# OLMo 2 7B models
allenai/OLMo-2-1124-7B-SFT:
  model_name: OLMo 2 7B SFT
  provider: huggingface
  release_date: 2024-11-24
  developer: AllenAI

allenai/OLMo-2-1124-7B-DPO:
  model_name: OLMo 2 7B DPO
  provider: huggingface
  release_date: 2024-11-24
  developer: AllenAI

allenai/OLMo-2-1124-7B:
  model_name: OLMo 2 7B RLVR
  provider: huggingface
  release_date: 2024-11-24
  developer: AllenAI

# OLMo 2 13B models
allenai/OLMo-2-1124-13B-SFT:
  model_name: OLMo 2 13B SFT
  provider: huggingface
  release_date: 2024-11-24
  developer: AllenAI

allenai/OLMo-2-1124-13B-DPO:
  model_name: OLMo 2 13B DPO
  provider: huggingface
  release_date: 2024-11-24
  developer: AllenAI

allenai/OLMo-2-1124-13B-Instruct:
  model_name: OLMo 2 13B RLVR
  provider: huggingface
  release_date: 2024-11-24
  developer: AllenAI

# OLMo 2 32B models
allenai/OLMo-2-0325-32B-SFT:
  model_name: OLMo 2 32B SFT
  provider: huggingface
  release_date: 2025-03-25
  developer: AllenAI

allenai/OLMo-2-0325-32B-DPO:
  model_name: OLMo 2 32B DPO
  provider: huggingface
  release_date: 2025-03-25
  developer: AllenAI

allenai/OLMo-2-0325-32B-Instruct:
  model_name: OLMo 2 32B RLVR
  provider: huggingface
  release_date: 2025-03-25
  developer: AllenAI

# Tülu 3 8B models
allenai/Llama-3.1-Tulu-3-8B-SFT:
  model_name: Tülu 3 8B SFT
  provider: huggingface
  release_date: 2024-11-21
  developer: AllenAI

allenai/Llama-3.1-Tulu-3-8B-DPO:
  model_name: Tülu 3 8B DPO
  provider: huggingface
  release_date: 2024-11-21
  developer: AllenAI

allenai/Llama-3.1-Tulu-3-8B:
  model_name: Tülu 3 8B RLVR
  provider: huggingface
  release_date: 2024-11-21
  developer: AllenAI

# Tülu 3 70B models
allenai/Llama-3.1-Tulu-3-70B-SFT:
  model_name: Tülu 3 70B SFT
  provider: huggingface
  release_date: 2024-11-21
  developer: AllenAI

allenai/Llama-3.1-Tulu-3-70B-DPO:
  model_name: Tülu 3 70B DPO
  provider: huggingface
  release_date: 2024-11-21
  developer: AllenAI

allenai/Llama-3.1-Tulu-3-70B:
  model_name: Tülu 3 70B RLVR
  provider: huggingface
  release_date: 2024-11-21
  developer: AllenAI

# Tülu V2.5 PPO models
allenai/tulu-v2.5-ppo-13b-hh-rlhf-60k:
  model_name: Tülu V2.5 13B PPO HH RLHF
  provider: huggingface
  release_date: 2024-06-11
  developer: AllenAI

allenai/tulu-v2.5-ppo-13b-chatbot-arena-2023:
  model_name: Tülu V2.5 13B PPO ChatbotArena
  provider: huggingface
  release_date: 2024-06-11
  developer: AllenAI

allenai/tulu-v2.5-ppo-13b-stackexchange-60k:
  model_name: Tülu V2.5 13B PPO StackExchange
  provider: huggingface
  release_date: 2024-06-11
  developer: AllenAI

allenai/tulu-v2.5-ppo-13b-nectar-60k:
  model_name: Tülu V2.5 13B PPO Nectar
  provider: huggingface
  release_date: 2024-06-11
  developer: AllenAI

# Tülu V2.5 DPO models
allenai/tulu-v2.5-dpo-13b-hh-rlhf-60k:
  model_name: Tülu V2.5 13B DPO HH RLHF
  provider: huggingface
  release_date: 2024-06-11
  developer: AllenAI

allenai/tulu-v2.5-dpo-13b-chatbot-arena-2023:
  model_name: Tülu V2.5 13B DPO ChatbotArena
  provider: huggingface
  release_date: 2024-06-11
  developer: AllenAI

allenai/tulu-v2.5-dpo-13b-stackexchange-60k:
  model_name: Tülu V2.5 13B DPO StackExchange
  provider: huggingface
  release_date: 2024-06-11
  developer: AllenAI

allenai/tulu-v2.5-dpo-13b-nectar-60k:
  model_name: Tülu V2.5 13B DPO Nectar
  provider: huggingface
  release_date: 2024-06-11
  developer: AllenAI

# Tülu 2 model
allenai/tulu-2-13b:
  model_name: Tülu 2 13B SFT
  provider: huggingface
  release_date: 2023-11-13
  developer: AllenAI

# Nous-Hermes models
NousResearch/Nous-Hermes-2-Mixtral-8x7B-SFT:
  model_name: Hermes 2 Mixtral 8x7B SFT
  provider: huggingface
  release_date: 2024-04-15
  developer: NousResearch

NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO:
  model_name: Hermes 2 Mixtral 8x7B DPO
  provider: huggingface
  release_date: 2024-04-15
  developer: NousResearch